### PR TITLE
Stroke Phenotype updates

### PR DESCRIPTION
**Pull request by deligkaris**
Some updates on the stroke phenotype branch. Some more work is left to do on this (see issue I opened on stroke phenotype for more information).

### CODE REVIEW

**Review by jburke5 — COMMENTED** [review]
i think this looks like a solid implementation of the idea of storing all of the outcome fields on the main population dataframe.

i think the main trick is that this isn't going to scale very well code-wise. if, for example, we added phenotype information for dementia, mi and epilepsy...we're going to have a ton of extra code in the population object.

my thought would be to have classes that know how to manage those fields for each outcome type.

so, for example, we coudl have a "StrokeOutcomeType" instead of stroke_object. And, for each stroke, the population would call the StrokeOutocmeType to set the stroke phenotype fields on the alive datafarme.

e.g. 

class StrokeOutcomeType

    def setPhenotypeFIelds(self, stroke, popDF):
        popDF['stroke_nihss'] = x
etc.

then, in population you'd have a look through all of hte OUtcomeTYpes and each one woudl call those methods.

the same thing coudl happen in reverse as well. the basic idea is to move all of the stroke specific code out of population and into the StrokeOutcomeType class.

combining this with separate classes for hte objects themselves (as we discussed) seems like it might make sense.

i'm not entirely sure this is sufficiently clear to work off. what to you think? should we chat or get a whit board out?

**Comment by deligkaris** [comment]
Regarding the class you refer to, I may have misunderstood your thoughts, but there is a chance what you are thinking is already implemented, so please correct me if I have misunderstood the first part of your note.

The advance_vectorized method adds the strokeNext column on the dataframe directly on the method but all other stroke
phenotype-related columns are added with a method that is part of the strokeOutcome.

outcomeVars = StrokeOutcome.add_outcome_vars(outcomeVars, len(alive))

The [class strokeOutcome](https://github.com/jburke5/microsim/blob/phenotype/microsim/stroke_outcome.py) has the method that adds columns on the alive dataframe.

The function [generate_stroke_outcome](https://github.com/jburke5/microsim/blob/phenotype/microsim/cv_outcome_determination.py#L152) is the one that will generate the stroke phenotypes (vectorized or not) and this function is part of the cv_outcome_determination class.

The only thing I see that could be moved away from the advance_vectorized method is to have the strokeOutcome class add the strokeNext column on the dataframe (in addition to the phenotype columns).

From what I understood, for the rest of the outcomes we would do something similar/equivalent to what we have already done for strokeOutcome.

(I still need to work on the stroke objects for the person objects).

**Comment by deligkaris** [comment]
Regarding pushing the stroke phenotype to person objects:

Currently, every person object has a dictionary _outcomes and there are 3 keys, one for each outcome (stroke, mi, dementia). The stroke key, has a value that is a list and stores tuples of stroke events (age, outcome type, fatal). The [update_person method](https://github.com/jburke5/microsim/blob/phenotype/microsim/population.py#L294) in population.py adds an object of the [class Outcome](https://github.com/jburke5/microsim/blob/phenotype/microsim/outcome.py#L4) to each person when there is an event. The class outcome has the attributes type, fatal and properties. Currently, we use type and fatal but not the properties attribute. I wonder if properties was built in to accommodate  the outcome phenotypes. 

If our plan is to use Outcome.properties then I think the only modifications needed would be to pass the stroke phenotype in the [update_person method](https://github.com/jburke5/microsim/blob/phenotype/microsim/population.py#L294) when there is a stroke event.

Would prefer a redesign of the current process (ie avoid using Outcome.properties for the phenotype)? (so we would leave mi and dementia to be taken care of using the class Outcome and have stroke events be registered using a StrokeOutcome class perhaps as a subclass of Outcome).

**Comment by jburke5** [comment]
1. i was describing exactly what you talked about with the StrokeOutcome setting phenotype variables on the alive datafame, it currently implemented just as I was thinking it should be. i wouldn’t make any changes there. this is a formula that we can follow with other object classes pretty easily — just add one line in population…that seems like it should work reasonably well.

2. you are also absolutely right that we thought about using the properties on Outcome as a place to store phenotype. and…again, i think that’s probably fine. if we were going to have a lot of code that required knowing data element types (i.e. we need one type of code for a binary and another type of code for continuous variables), then i think we’d need more — not just a variable name and value, but also some type information. but, i think we probably don’t need type information any time soon…so, it think this works for now!

so, i really do like this framework and think it’ll work well!

**Comment by deligkaris** [comment]
A possible issue on gcp random effect:

[Population.py is using get_gcp_vectorized](https://github.com/jburke5/microsim/blob/phenotype/microsim/population.py#L207) which includes [a gcpRandomEffect](https://github.com/jburke5/microsim/blob/phenotype/microsim/outcome_model_repository.py#L164) and then the [get_risk_for_person of the gcp_model](https://github.com/jburke5/microsim/blob/phenotype/microsim/outcome_model_repository.py#L164) includes another random effect and I am not sure if those two random effects represent something different or not. 

One is using person.gcpRandomEffect and the other one is using the dictionary person._randomEffects that includes the "gcp" key...but I think the first one is just a column from the dataframe [(also see here)](https://github.com/jburke5/microsim/blob/phenotype/microsim/person.py#L302) whereas the second one is a person attribute.

So it is possible the code is now adding the same thing two times but I am not entirely certain....

**Comment by jburke5** [comment]
you gave me a heart attack there for a minute, but i think we’re ok…

when you look at this method in the model: https://github.com/jburke5/microsim/blob/d487de6f15072156e7cff223cae9957a734e9251/microsim/gcp_model.py#L107

i thikn the get_risk_for_person() only ends up adding the gcp IF it is non-vectorized. the if statement on line 110 means that random_effect is zero if it is run in a vectorized setting…so, its only adding it at the end.

looking at this, though, it’d be cleaner to move the random effect to the person row wrapper and then access it all in the gcp model as opposed to having the random effect be implemented in the repository — that’s a lousy place to have substantive logic…

jim

**Pull request merged**
